### ISSUE TITLE
Error in if (detected_peaks_l[p, i + 1]) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by pvervliet** [ermueller/SAX_Gap_Filling#1]
Hi,

I am trying to run the SAXGAP function with the following (default) parameters;
`SAXGAP(peak_table = ForSAXGAP,
               mzML_filenames = files,
               SAXGAP_params = list(a = 6, #Alphabet size
                                    w = 6,
                                    t = 14,
                                    pe = 0.9,
                                    intensity_threshold = 10000,
                                    dppm = 5))`

However, I get the following error:
`Error in if (detected_peaks_l[p, i + 1]) { : 
  missing value where TRUE/FALSE needed`

The peak_table is a data.table with columns mz & RT (general), Intensity columns per sample and retention time columns per sample. Filenames are stored in the vector "files". 

Do you have any input how to proceed?
 
Thank you in advance,
Philippe

**Comment by ermueller** [comment]
Hello Philippe,

From the looks of it, everything is correct about your inputs. Can you upload the example table you created? (Or the first 100 lines of it, if the error is also reproducible with that) It's easier to find an error if I can debug it directly.  

Even if something about the table is not according to the specified input, I would have to add another check to the script to catch this error.

Thank you very much,
Erik

**Comment by pvervliet** [comment]
Hi Erik,

Attached is a csv of the peak table I use. 
I randomly selected 100 rows of the complete table.

[ForSAXGAP-100rows.csv.zip](https://github.com/ermueller/SAX_Gap_Filling/files/5089922/ForSAXGAP-100rows.csv.zip)

Kind regards,
Philippe

**Comment by ermueller** [comment]
Hello Philippe,

I fixed the issue - I did not properly describe that the table should not contain NAs, but zeroes instead. I fixed this problem, so now the package autodetects the NAs and replaces them, meaning that with the current version of the package you can just leave the table as is and it should work.

Best Wishes,
Erik

**Comment by pvervliet** [comment]
Hi Erik,

I just tested with the current version and SAXGAP runs without errors. 

Thank you for resolving so quickly,
Philippe
